### ISSUE TITLE
Howto use role's variables?

### ISSUE THREAD

**Issue by harenber** [JakobLichterfeld/ansible-role-winehq#1]
**Describe the bug**
Cannot use variables with the dot inside. 

**To Reproduce**
Have this in my Playbook:
```yaml
  tasks:
    - include_role:
        name: jakoblichterfeld.winehq
      vars:
        winehq.install_playonlinux: false
```

But Ansible (version is: ansible [core 2.17.6]) doesn't like these "nested" variable with the dot:

```
ERROR! Invalid variable name in vars specified for IncludeRole: 'winehq.install_playonlinux' is not a valid variable name. 'winehq.install_playonlinux' is not a valid variable name

The error appears to be in '/Users/12345/private/ansible/plus/plus.yaml': line 23, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      vars:
        winehq.install_playonlinux: false
        ^ here
```

If there is a different syntax to be used in the playbook, it may be worth mentioning in the documentation? At least I never have used a role before which used that, so I have no idea how to use this correctly.

**Information:**
```
harenber@dhcp-109-37 plus % ansible --version
ansible [core 2.17.6]
  config file = None
  configured module search path = ['/Users/12345/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.6.0_1/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/12345/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)] (/opt/homebrew/Cellar/ansible/10.6.0_1/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. Correct syntax is (that's how you nest variables in yml)

```yaml
      vars:
        winehq:
           install_playonlinux: false
```
